"""empty message

Revision ID: 04a1e3996645
Revises: 193ded870f57
Create Date: 2020-11-09 18:03:29.351485

"""

# revision identifiers, used by Alembic.
revision = '04a1e3996645'
down_revision = '193ded870f57'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
