"""added new columns

Revision ID: 1722f0245868
Revises: e7b24f29d507
Create Date: 2020-11-09 02:49:46.495626

"""

# revision identifiers, used by Alembic.
revision = '1722f0245868'
down_revision = 'e7b24f29d507'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
