"""added new columns

Revision ID: 700525a49826
Revises: 1722f0245868
Create Date: 2020-11-09 02:53:50.813296

"""

# revision identifiers, used by Alembic.
revision = '700525a49826'
down_revision = '1722f0245868'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('art_history', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('bars', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('chinese', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('concerts', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('dessert', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('dining', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('entertainment', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('extreme_sports', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('healthy', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('hiking', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('kayaking', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('movies', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('nature', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('outside_campus', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('science_tech', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('sports', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sports')
    op.drop_column('users', 'science_tech')
    op.drop_column('users', 'outside_campus')
    op.drop_column('users', 'nature')
    op.drop_column('users', 'movies')
    op.drop_column('users', 'kayaking')
    op.drop_column('users', 'hiking')
    op.drop_column('users', 'healthy')
    op.drop_column('users', 'extreme_sports')
    op.drop_column('users', 'entertainment')
    op.drop_column('users', 'dining')
    op.drop_column('users', 'dessert')
    op.drop_column('users', 'concerts')
    op.drop_column('users', 'chinese')
    op.drop_column('users', 'bars')
    op.drop_column('users', 'art_history')
    # ### end Alembic commands ###
