"""empty message

Revision ID: 74b6bb68e1ce
Revises: 04a1e3996645
Create Date: 2020-11-09 18:06:25.045678

"""

# revision identifiers, used by Alembic.
revision = '74b6bb68e1ce'
down_revision = '04a1e3996645'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attraction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attraction_name', sa.String(length=64), nullable=True),
    sa.Column('address', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=12), nullable=True),
    sa.Column('about_me', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('image', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attraction_attraction_name'), 'attraction', ['attraction_name'], unique=True)
    op.create_table('hike',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hike_name', sa.String(length=64), nullable=True),
    sa.Column('trail_head', sa.String(length=64), nullable=True),
    sa.Column('about_me', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('image', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hike_hike_name'), 'hike', ['hike_name'], unique=True)
    op.create_table('restaurant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_name', sa.String(length=64), nullable=True),
    sa.Column('address', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=12), nullable=True),
    sa.Column('about_me', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('image', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_restaurant_restaurant_name'), 'restaurant', ['restaurant_name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_restaurant_restaurant_name'), table_name='restaurant')
    op.drop_table('restaurant')
    op.drop_index(op.f('ix_hike_hike_name'), table_name='hike')
    op.drop_table('hike')
    op.drop_index(op.f('ix_attraction_attraction_name'), table_name='attraction')
    op.drop_table('attraction')
    # ### end Alembic commands ###
